apiVersion: v1
kind: Pod
metadata:
  name: guestbook-gui
  labels:
    app: guestbook-gui
spec:
  containers:
    - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
      imagePullPolicy: IfNotPresent
      name: guestbook-ui
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
  restartPolicy: Always
