apiVersion: v1
kind: Service
metadata:
  name: guestbook-gui
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
      protocol: TCP
  selector:
    app: guestbook-gui
  type: LoadBalancer